server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: social-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/social_platform
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secretKey: "OrrFKp3pUsbmMtf+90Q5/XdeZwvAc2Hg0NXJyx/c9+RX6tI/LNUv8c7t3uye8CGe"